import { PlanFeatures, PlanLimits, SubscriptionPlan } from '../types/domain';
export declare const API_VERSION = "v1";
export declare const DEFAULT_PAGE_SIZE = 20;
export declare const MAX_PAGE_SIZE = 100;
export declare const ACCESS_TOKEN_EXPIRY = 3600;
export declare const REFRESH_TOKEN_EXPIRY = 2592000;
export declare const DEFAULT_CONFIDENCE_THRESHOLD = 0.7;
export declare const MIN_CONFIDENCE_FOR_AUTO_RESPONSE = 0.75;
export declare const DEFAULT_TOP_K_RESULTS = 5;
export declare const CHUNK_SIZE = 500;
export declare const CHUNK_OVERLAP = 50;
export declare const MAX_CALL_DURATION_SECONDS = 1800;
export declare const SMS_MAX_LENGTH = 1600;
export declare const PHONE_REGEX: RegExp;
export declare const TRIAL_DURATION_DAYS = 14;
export declare const MAX_KNOWLEDGE_ITEMS_PER_COMPANY = 500;
export declare const MAX_CALLS_PER_MONTH_TRIAL = 100;
export declare const MAX_RECORDING_SIZE_MB = 50;
export declare const ALLOWED_AUDIO_FORMATS: string[];
export declare const RECORDING_RETENTION_DAYS = 90;
export declare const PLAN_LIMITS: Record<SubscriptionPlan, PlanLimits>;
export declare const PLAN_FEATURES: Record<SubscriptionPlan, PlanFeatures>;
export declare const ERROR_CODES: {
    readonly INVALID_CREDENTIALS: "AUTH001";
    readonly TOKEN_EXPIRED: "AUTH002";
    readonly INSUFFICIENT_PERMISSIONS: "AUTH003";
    readonly INVALID_INPUT: "VAL001";
    readonly MISSING_REQUIRED_FIELD: "VAL002";
    readonly RESOURCE_NOT_FOUND: "BIZ001";
    readonly DUPLICATE_RESOURCE: "BIZ002";
    readonly OPERATION_NOT_ALLOWED: "BIZ003";
    readonly QUOTA_EXCEEDED: "BIZ004";
    readonly TELEPHONY_ERROR: "EXT001";
    readonly LLM_ERROR: "EXT002";
    readonly STORAGE_ERROR: "EXT003";
    readonly INTERNAL_ERROR: "SYS001";
    readonly DATABASE_ERROR: "SYS002";
};
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
//# sourceMappingURL=constants.d.ts.map