import type { CategoryIconSlug } from '@/lib/category-icons';

export type ServiceGroup = {
  key: string;
  title: string;
  titleAr: string;
  /** Icon slug — maps to CATEGORY_ICON_MAP in lib/category-icons.tsx. No emoji. */
  iconSlug: CategoryIconSlug;
  slug: string;
  proCount?: string;
  description: string;
  services: string[];
  arServices?: string[];
};

export const HOME_SERVICE_GROUPS: ServiceGroup[] = [
  {
    key: 'ac-hvac',
    title: 'AC & HVAC',
    titleAr: 'تكييف وتبريد',
    iconSlug: 'ac-repair',
    slug: 'ac-repair',
    description: 'AC installation, repair, maintenance, and ventilation.',
    services: [
      'AC Repair',
      'AC Installation',
      'AC Maintenance',
      'AC Deep Cleaning',
      'Duct Cleaning',
      'Central AC Systems',
      'Split AC Unit Install',
      'Ventilation Systems',
      'Smart Thermostat Install',
      'HVAC Inspection',
    ],
  },
  {
    key: 'plumbing',
    title: 'Plumbing',
    titleAr: 'سباكة',
    iconSlug: 'plumbing',
    slug: 'plumbing',
    description: 'Pipe repair, water heaters, fixtures, and drain cleaning.',
    services: [
      'Plumbing Repair',
      'Pipe Installation',
      'Pipe Repair',
      'Drain Cleaning',
      'Water Heater Repair',
      'Water Heater Installation',
      'Bathroom Fixtures Install',
      'Kitchen Plumbing',
      'Leak Detection',
      'Faucet Repair',
      'Toilet Repair',
      'Shower Install',
      'Water Pump Service',
      'Water Tank Cleaning',
      'Sewer Line Cleaning',
    ],
  },
  {
    key: 'electrical',
    title: 'Electrical',
    titleAr: 'كهرباء',
    iconSlug: 'electrical',
    slug: 'electrical',
    description: 'Wiring, lighting, circuit breakers, and smart home.',
    services: [
      'Electrical Repair',
      'Outlet Installation',
      'Switch Repair',
      'Lighting Installation',
      'Wiring & Rewiring',
      'Circuit Breaker Repair',
      'Fuse Box Upgrade',
      'Ceiling Fan Install',
      'EV Charger Installation',
      'Generator Installation',
      'Smart Home Wiring',
      'Electrical Panel Upgrade',
      'Outdoor Lighting',
      'Security Lighting',
      'Electrical Inspection',
    ],
  },
  {
    key: 'house-cleaning',
    title: 'House Cleaning',
    titleAr: 'تنظيف منازل',
    iconSlug: 'cleaning',
    slug: 'cleaning',
    description: 'Regular, deep, move-in/out, and specialty cleaning.',
    services: [
      'House Cleaning',
      'Regular Cleaning',
      'Deep Cleaning',
      'Move-In Cleaning',
      'Move-Out Cleaning',
      'Post-Construction Cleaning',
      'Maid Service',
      'Sofa Cleaning',
      'Mattress Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Kitchen Deep Clean',
      'Bathroom Cleaning',
      'Villa Cleaning',
      'Office Cleaning',
      'Eid Cleaning',
    ],
  },
  {
    key: 'painting',
    title: 'Painting',
    titleAr: 'دهان',
    iconSlug: 'painting',
    slug: 'painting',
    description: 'Interior, exterior, texture, and specialty finishes.',
    services: [
      'Interior Painting',
      'Exterior Painting',
      'Wall Texture',
      'Wallpaper Removal',
      'Epoxy Floor Coating',
      'Stucco Application',
      'Decorative Painting',
      'Ceiling Painting',
      'Villa Painting',
      'Apartment Painting',
      'Touch-Up Painting',
    ],
  },
  {
    key: 'carpentry',
    title: 'Carpentry',
    titleAr: 'نجارة',
    iconSlug: 'carpentry',
    slug: 'carpentry',
    description: 'Furniture, cabinets, doors, shelving, and custom woodwork.',
    services: [
      'Furniture Assembly',
      'Custom Furniture',
      'Door Installation',
      'Door Repair',
      'Cabinet Installation',
      'Kitchen Cabinet Install',
      'Closet Build',
      'Shelving Install',
      'Wood Flooring',
      'Staircase Repair',
      'Window Frame Repair',
      'Wardrobe Install',
      'Gypsum Board Work',
      'False Ceiling',
    ],
  },
  {
    key: 'pest-control',
    title: 'Pest Control',
    titleAr: 'مكافحة حشرات',
    iconSlug: 'pest-control',
    slug: 'pest-control',
    description: 'Cockroach, termite, rodent, scorpion, and mosquito control.',
    services: [
      'Pest Control',
      'Cockroach Control',
      'Termite Treatment',
      'Bed Bug Treatment',
      'Rodent Control',
      'Mosquito Control',
      'Scorpion Control',
      'Ant Control',
      'Fly Control',
      'General Fumigation',
      'Pest Inspection',
      'Fumigation Certificate',
    ],
  },
  {
    key: 'landscaping',
    title: 'Landscaping',
    titleAr: 'تنسيق حدائق',
    iconSlug: 'landscaping',
    slug: 'landscaping',
    description: 'Garden design, lawn care, trees, and irrigation.',
    services: [
      'Garden Design',
      'Lawn Maintenance',
      'Tree Trimming',
      'Tree Removal',
      'Irrigation System Install',
      'Irrigation Repair',
      'Artificial Grass Install',
      'Outdoor Lighting Install',
      'Palm Tree Care',
      'Hedge Trimming',
      'Soil & Fertilization',
      'Paving & Walkways',
      'Garden Cleanup',
      'Pergola Install',
    ],
  },
  {
    key: 'car-washing',
    title: 'Car Washing & Detailing',
    titleAr: 'غسيل وتلميع السيارات',
    iconSlug: 'car-washing',
    slug: 'car-washing',
    description: 'Mobile car wash, full detail, polish, and interior cleaning.',
    services: [
      'Car Washing',
      'Mobile Car Wash',
      'Full Car Detail',
      'Interior Car Cleaning',
      'Exterior Car Wash',
      'Engine Cleaning',
      'Car Polishing',
      'Paint Protection Film',
      'Ceramic Coating',
      'Windshield Cleaning',
      'Upholstery Cleaning',
      'Steam Car Cleaning',
    ],
  },
  {
    key: 'appliance-repair',
    title: 'Appliance Repair',
    titleAr: 'إصلاح الأجهزة',
    iconSlug: 'appliance-repair',
    slug: 'appliance-repair',
    description: 'Washing machine, dryer, fridge, oven, and more.',
    services: [
      'Appliance Repair',
      'Washing Machine Repair',
      'Dryer Repair',
      'Washer & Dryer Repair',
      'Refrigerator Repair',
      'Dishwasher Repair',
      'Oven Repair',
      'Stove Repair',
      'Microwave Repair',
      'Water Heater Repair',
      'Water Dispenser Repair',
      'Air Fryer Repair',
      'Vacuum Repair',
      'TV Mounting',
      'TV Repair',
    ],
  },
  {
    key: 'moving',
    title: 'Moving & Delivery',
    titleAr: 'نقل وتوصيل',
    iconSlug: 'moving',
    slug: 'moving',
    description: 'Home moving, furniture delivery, packing, and storage.',
    services: [
      'Home Moving',
      'Office Moving',
      'Furniture Moving',
      'Furniture Delivery',
      'Box Packing Service',
      'Unpacking Service',
      'Heavy Item Moving',
      'Piano Moving',
      'Same-Day Delivery',
      'Storage Solutions',
      'Junk Removal',
      'Assembly & Placement',
    ],
  },
  {
    key: 'tile-flooring',
    title: 'Tile & Flooring',
    titleAr: 'سيراميك وأرضيات',
    iconSlug: 'tile-flooring',
    slug: 'tile-flooring',
    description: 'Tile installation, marble polishing, and floor repairs.',
    services: [
      'Tile Installation',
      'Tile Repair',
      'Bathroom Tiling',
      'Kitchen Tiling',
      'Marble Polishing',
      'Marble Repair',
      'Hardwood Flooring',
      'Vinyl Flooring',
      'Epoxy Flooring',
      'Grout Repair',
      'Porcelain Tile',
      'Floor Polishing',
      'Outdoor Tiling',
    ],
  },
  {
    key: 'security-systems',
    title: 'Security Systems',
    titleAr: 'أنظمة الأمان',
    iconSlug: 'security',
    slug: 'security',
    description: 'CCTV, alarm systems, smart locks, and access control.',
    services: [
      'CCTV Installation',
      'Security Camera Install',
      'Alarm System Install',
      'Smart Lock Install',
      'Intercom System',
      'Access Control System',
      'Home Automation',
      'Safe Installation',
      'Video Doorbell Install',
      'Motion Sensor Install',
    ],
  },
  {
    key: 'doors-windows',
    title: 'Doors & Windows',
    titleAr: 'أبواب ونوافذ',
    iconSlug: 'doors-windows',
    slug: 'doors-windows',
    description: 'Door and window installation, repair, and glazing.',
    services: [
      'Door Installation',
      'Door Repair',
      'Window Installation',
      'Window Repair',
      'Glass Replacement',
      'Double Glazing',
      'Screen / Mesh Repair',
      'Lock Change',
      'Door Frame Repair',
      'Sliding Door Repair',
      'Roller Shutter Install',
      'Automatic Door Install',
    ],
  },
  {
    key: 'bathroom-renovation',
    title: 'Bathroom Renovation',
    titleAr: 'تجديد الحمام',
    iconSlug: 'bathroom',
    slug: 'bathroom',
    description: 'Full remodels, fixtures, shower, and waterproofing.',
    services: [
      'Bathroom Renovation',
      'Full Bathroom Remodel',
      'Shower Installation',
      'Bathtub Install',
      'Vanity Install',
      'Mirror Install',
      'Toilet Replacement',
      'Bathroom Waterproofing',
      'Bathroom Tiling',
      'Grab Bar Install',
    ],
  },
  {
    key: 'handyman',
    title: 'Handyman',
    titleAr: 'أعمال المنزل العامة',
    iconSlug: 'handyman',
    slug: 'handyman',
    description: 'General repairs, assembly, mounting, and home fixes.',
    services: [
      'Handyman Services',
      'Furniture Assembly',
      'TV Mounting',
      'Picture Hanging',
      'Shelf Installation',
      'Curtain & Blind Install',
      'Minor Repairs',
      'Gypsum Work',
      'False Ceiling Repair',
      'Caulking & Sealing',
      'Touch-Up Repairs',
      'Door Hinge Repair',
      'Locksmith Services',
    ],
  },
  {
    key: 'pool-water',
    title: 'Pool & Water Features',
    titleAr: 'أحواض السباحة',
    iconSlug: 'pool-service',
    slug: 'pool-service',
    description: 'Pool cleaning, maintenance, repair, and water features.',
    services: [
      'Pool Cleaning',
      'Pool Maintenance',
      'Pool Repair',
      'Pool Chemical Balancing',
      'Fountain Maintenance',
      'Water Feature Install',
      'Pool Filter Service',
      'Jacuzzi Repair',
    ],
  },
  {
    key: 'roofing-waterproofing',
    title: 'Roofing & Waterproofing',
    titleAr: 'أسطح وعزل مائي',
    iconSlug: 'roofing',
    slug: 'roofing',
    description: 'Roof repair, waterproofing, thermal insulation, and leaks.',
    services: [
      'Roof Repair',
      'Waterproofing',
      'Thermal Insulation',
      'Leak Repair',
      'Roof Coating',
      'Foam Insulation',
      'Roof Inspection',
      'Flat Roof Repair',
      'Heat Insulation',
    ],
  },
  {
    key: 'curtains-blinds',
    title: 'Curtains & Blinds',
    titleAr: 'ستائر وبلايند',
    iconSlug: 'curtains-blinds',
    slug: 'curtains-blinds',
    description: 'Curtain and blind installation, cleaning, and motorized options.',
    services: [
      'Curtain Installation',
      'Blind Installation',
      'Roller Blind Install',
      'Curtain Cleaning',
      'Motorized Blinds',
      'Sheer Curtain Hang',
      'Curtain Rail Install',
      'Blackout Curtain Install',
    ],
  },
  {
    key: 'sanitation',
    title: 'Tank & Sanitation',
    titleAr: 'الصرف الصحي والخزانات',
    iconSlug: 'sanitation',
    slug: 'sanitation',
    description: 'Water tank cleaning, septic service, and drain sanitation.',
    services: [
      'Water Tank Cleaning',
      'Septic Tank Cleaning',
      'Grease Trap Cleaning',
      'Sewer Cleaning',
      'Drain Unblocking',
      'Sewage Pump Service',
      'Sanitation Inspection',
    ],
  },
  {
    key: 'nanny-childcare',
    title: 'Nanny & Childcare',
    titleAr: 'خادمة ومربية أطفال',
    iconSlug: 'nanny-childcare',
    slug: 'nanny-childcare',
    description: 'Nannies, babysitters, elderly care, and special needs support.',
    services: [
      'Nanny Service',
      'Live-In Nanny',
      'Babysitting',
      'Newborn Care',
      'Elderly Care',
      'Special Needs Care',
      'After-School Care',
      'Overnight Babysitting',
    ],
  },
  {
    key: 'private-tutoring',
    title: 'Private Tutoring',
    titleAr: 'دروس خصوصية',
    iconSlug: 'private-tutoring',
    slug: 'private-tutoring',
    description: 'Home tutoring for all grades, Quran teaching, and language lessons.',
    services: [
      'Math Tutoring',
      'Science Tutoring',
      'Arabic Language Tutor',
      'English Tutor',
      'Quran Teaching',
      'Elementary Tutoring',
      'High School Tutoring',
      'University Tutoring',
      'Online Tutoring',
      'French Tutor',
      'Exam Preparation',
    ],
  },
  {
    key: 'driver-services',
    title: 'Driver Services',
    titleAr: 'خدمات السائق',
    iconSlug: 'driver-services',
    slug: 'driver-services',
    description: 'Personal drivers, school runs, airport transfers, and delivery.',
    services: [
      'Personal Driver',
      'Part-Time Driver',
      'Full-Time Driver',
      'School Run',
      'Airport Transfer',
      'Shopping Driver',
      'Medical Appointment Driver',
      'Corporate Driver',
      'Event Driver',
    ],
  },
  {
    key: 'network-it',
    title: 'Network & IT Setup',
    titleAr: 'شبكات وتقنية',
    iconSlug: 'network-it',
    slug: 'network-it',
    description: 'Home network setup, mesh Wi-Fi, ethernet cabling, and smart devices.',
    services: [
      'Router Setup',
      'Mesh Wi-Fi Install',
      'Ethernet Cabling',
      'Smart TV Setup',
      'Home Network Setup',
      'Wi-Fi Extender Install',
      'CCTV Network Setup',
      'IT Support at Home',
      'Structured Cabling',
      'Fiber Optic Install',
      'Network Troubleshooting',
    ],
  },
  {
    key: 'healthcare-home',
    title: 'Healthcare at Home',
    titleAr: 'رعاية صحية منزلية',
    iconSlug: 'healthcare-home',
    slug: 'healthcare-home',
    description: 'Nursing care, blood tests, physiotherapy, and IV drips at home.',
    services: [
      'Home Nursing',
      'Blood Test at Home',
      'IV Drip at Home',
      'Physiotherapy',
      'Wound Care',
      'Post-Surgery Care',
      'Diabetes Care',
      'Blood Pressure Monitoring',
      'Dietitian Consultation',
      'Home Doctor Visit',
      'Vaccination at Home',
      'Medical Equipment Rental',
    ],
  },
  {
    key: 'laundry-ironing',
    title: 'Laundry & Ironing',
    titleAr: 'غسيل وكي',
    iconSlug: 'laundry-ironing',
    slug: 'laundry-ironing',
    description: 'Pickup and delivery laundry, dry cleaning, and ironing services.',
    services: [
      'Laundry Service',
      'Ironing Service',
      'Dry Cleaning',
      'Laundry Pickup & Delivery',
      'Curtain Laundry',
      'Bedding Wash',
      'Suit Dry Cleaning',
      'Shoe Cleaning',
      'Carpet Dry Cleaning',
    ],
  },
  {
    key: 'photography-video',
    title: 'Photography & Video',
    titleAr: 'تصوير وفيديو',
    iconSlug: 'photography-video',
    slug: 'photography-video',
    description: 'Family portraits, events, real estate, and video production.',
    services: [
      'Family Photography',
      'Wedding Photography',
      'Event Photography',
      'Real Estate Photography',
      'Product Photography',
      'Video Production',
      'Drone Photography',
      'Portrait Session',
      'Birthday Photography',
      'Graduation Photography',
    ],
  },
  {
    key: 'personal-training',
    title: 'Personal Training',
    titleAr: 'تدريب رياضي',
    iconSlug: 'personal-training',
    slug: 'personal-training',
    description: 'Personal trainers, yoga instructors, and fitness coaches at home.',
    services: [
      'Personal Trainer',
      'Home Gym Setup',
      'Yoga Instructor',
      'Pilates at Home',
      'Weight Loss Coaching',
      'Strength Training',
      'Kids Fitness',
      'Nutrition Coaching',
      'Stretching & Mobility',
      'Swimming Coach',
    ],
  },
  {
    key: 'locksmith-keys',
    title: 'Locksmith & Keys',
    titleAr: 'أقفال ومفاتيح',
    iconSlug: 'security',
    slug: 'locksmith',
    description: 'Lock repair, key duplication, smart locks, and emergency lockouts.',
    services: [
      'Emergency Lockout',
      'Lock Change',
      'Lock Repair',
      'Key Duplication',
      'Smart Lock Install',
      'Digital Door Lock',
      'Safe Opening',
      'Mailbox Lock',
      'Car Key Programming',
      'Master Key System',
      'Villa Gate Lock',
    ],
  },
  {
    key: 'garage-gates',
    title: 'Garage Doors & Gates',
    titleAr: 'أبواب كراج وبوابات',
    iconSlug: 'doors-windows',
    slug: 'garage-doors-gates',
    description: 'Garage doors, automatic gates, motors, remotes, and barriers.',
    services: [
      'Garage Door Repair',
      'Garage Door Install',
      'Automatic Gate Repair',
      'Gate Motor Installation',
      'Gate Remote Programming',
      'Rolling Shutter Repair',
      'Parking Barrier Install',
      'Fence Gate Repair',
      'Garage Spring Repair',
    ],
  },
  {
    key: 'kitchen-renovation',
    title: 'Kitchen Renovation',
    titleAr: 'تجديد المطابخ',
    iconSlug: 'carpentry',
    slug: 'kitchen-renovation',
    description: 'Kitchen remodeling, cabinets, countertops, sinks, and appliance fitting.',
    services: [
      'Kitchen Renovation',
      'Kitchen Cabinet Install',
      'Countertop Install',
      'Sink Installation',
      'Kitchen Island Build',
      'Backsplash Installation',
      'Kitchen Hood Install',
      'Pantry Shelving',
      'Cabinet Refacing',
    ],
  },
  {
    key: 'masonry-concrete',
    title: 'Masonry & Concrete',
    titleAr: 'بناء وخرسانة',
    iconSlug: 'tile-flooring',
    slug: 'masonry-concrete',
    description: 'Block work, plastering, concrete repair, and small structural jobs.',
    services: [
      'Block Wall Construction',
      'Concrete Repair',
      'Concrete Pouring',
      'Plastering',
      'Cement Board Work',
      'Wall Crack Repair',
      'Stair Concrete Repair',
      'Driveway Repair',
      'Concrete Cutting',
      'Masonry Repair',
    ],
  },
  {
    key: 'metal-welding',
    title: 'Metalwork & Welding',
    titleAr: 'حدادة ولحام',
    iconSlug: 'handyman',
    slug: 'metalwork-welding',
    description: 'Welding, railings, metal doors, grilles, stairs, and custom fabrication.',
    services: [
      'Welding Repair',
      'Metal Door Fabrication',
      'Window Grill Install',
      'Stair Railing Install',
      'Balcony Railing',
      'Steel Structure Repair',
      'Pergola Welding',
      'Custom Metal Shelves',
      'Gate Fabrication',
    ],
  },
  {
    key: 'glass-mirrors',
    title: 'Glass & Mirrors',
    titleAr: 'زجاج ومرايا',
    iconSlug: 'doors-windows',
    slug: 'glass-mirrors',
    description: 'Glass partitions, mirrors, shower glass, tabletops, and replacement.',
    services: [
      'Glass Replacement',
      'Mirror Installation',
      'Shower Glass Install',
      'Glass Partition',
      'Glass Door Repair',
      'Tabletop Glass',
      'Shopfront Glass',
      'Tempered Glass Install',
      'Glass Railing',
    ],
  },
  {
    key: 'upholstery-furniture',
    title: 'Upholstery & Furniture Repair',
    titleAr: 'تنجيد وإصلاح أثاث',
    iconSlug: 'carpentry',
    slug: 'upholstery-furniture',
    description: 'Sofa upholstery, cushion repair, furniture restoration, and leather care.',
    services: [
      'Sofa Upholstery',
      'Chair Upholstery',
      'Leather Sofa Repair',
      'Cushion Replacement',
      'Furniture Restoration',
      'Bed Frame Repair',
      'Dining Chair Repair',
      'Office Chair Repair',
      'Fabric Replacement',
    ],
  },
  {
    key: 'smart-home',
    title: 'Smart Home & Automation',
    titleAr: 'المنزل الذكي',
    iconSlug: 'network-it',
    slug: 'smart-home',
    description: 'Smart lighting, sensors, locks, thermostats, hubs, and automations.',
    services: [
      'Smart Home Setup',
      'Smart Lighting Install',
      'Smart Switch Install',
      'Smart Thermostat Install',
      'Smart Lock Install',
      'Smart Curtain Setup',
      'Home Assistant Setup',
      'Voice Assistant Setup',
      'Smart Sensor Install',
    ],
  },
  {
    key: 'solar-energy',
    title: 'Solar & Energy',
    titleAr: 'طاقة شمسية وكهرباء احتياطية',
    iconSlug: 'electrical',
    slug: 'solar-energy',
    description: 'Solar panels, batteries, inverters, backup power, and energy checks.',
    services: [
      'Solar Panel Installation',
      'Solar Panel Cleaning',
      'Inverter Repair',
      'Battery Backup Install',
      'UPS Installation',
      'Energy Audit',
      'Solar Water Heater',
      'Generator Maintenance',
      'Power Backup Setup',
    ],
  },
  {
    key: 'gas-services',
    title: 'Gas Services',
    titleAr: 'خدمات الغاز',
    iconSlug: 'appliance-repair',
    slug: 'gas-services',
    description: 'Gas line checks, stove connection, leak inspection, and cylinder setup.',
    services: [
      'Gas Stove Connection',
      'Gas Leak Inspection',
      'Gas Line Repair',
      'Gas Cylinder Setup',
      'Outdoor Kitchen Gas',
      'Gas Regulator Replacement',
      'Gas Safety Check',
      'Cooktop Installation',
    ],
  },
  {
    key: 'disinfection-odor',
    title: 'Disinfection & Odor Removal',
    titleAr: 'تعقيم وإزالة روائح',
    iconSlug: 'cleaning',
    slug: 'disinfection-odor-removal',
    description: 'Home sanitizing, mold treatment, odor removal, and air purification.',
    services: [
      'Home Disinfection',
      'Mold Treatment',
      'Odor Removal',
      'Smoke Odor Removal',
      'Pet Odor Removal',
      'Air Duct Sanitizing',
      'Bathroom Mold Cleaning',
      'Kitchen Sanitizing',
      'Move-In Sanitizing',
    ],
  },
  {
    key: 'pressure-washing',
    title: 'Pressure Washing',
    titleAr: 'غسيل بالضغط',
    iconSlug: 'sanitation',
    slug: 'pressure-washing',
    description: 'Exterior washing for driveways, walls, roofs, patios, and facades.',
    services: [
      'Driveway Pressure Washing',
      'Facade Washing',
      'Patio Cleaning',
      'Roof Washing',
      'Boundary Wall Cleaning',
      'Outdoor Tile Cleaning',
      'Garage Floor Cleaning',
      'Restaurant Exterior Cleaning',
    ],
  },
  {
    key: 'fencing-shades',
    title: 'Fencing, Awnings & Shades',
    titleAr: 'أسوار ومظلات',
    iconSlug: 'roofing',
    slug: 'fencing-awnings-shades',
    description: 'Fences, privacy screens, awnings, car shades, and outdoor covers.',
    services: [
      'Fence Installation',
      'Fence Repair',
      'Privacy Screen Install',
      'Car Shade Install',
      'Awning Installation',
      'Canopy Repair',
      'Outdoor Shade Structure',
      'Pool Fence Install',
      'Balcony Screen',
    ],
  },
  {
    key: 'decor-wall-panels',
    title: 'Decor & Wall Panels',
    titleAr: 'ديكور وألواح جدران',
    iconSlug: 'painting',
    slug: 'decor-wall-panels',
    description: 'Wall panels, wallpaper, gypsum decor, feature walls, and finishes.',
    services: [
      'Wallpaper Installation',
      'Wall Panel Install',
      '3D Wall Panels',
      'Gypsum Decoration',
      'Feature Wall Design',
      'TV Wall Build',
      'Acoustic Panel Install',
      'Decorative Molding',
      'Wall Cladding',
    ],
  },
  {
    key: 'pet-care',
    title: 'Pet Care at Home',
    titleAr: 'رعاية الحيوانات الأليفة',
    iconSlug: 'handyman',
    slug: 'pet-care',
    description: 'Pet sitting, grooming, walking, litter setup, and home pet care.',
    services: [
      'Pet Sitting',
      'Dog Walking',
      'Cat Sitting',
      'Pet Grooming at Home',
      'Aquarium Cleaning',
      'Bird Cage Cleaning',
      'Pet Taxi',
      'Litter Box Setup',
      'Pet Feeding Visits',
    ],
  },
  {
    key: 'beauty-home',
    title: 'Beauty at Home',
    titleAr: 'تجميل منزلي',
    iconSlug: 'personal-training',
    slug: 'beauty-at-home',
    description: 'At-home grooming, hair, makeup, nails, and personal care appointments.',
    services: [
      'Hair Styling at Home',
      'Makeup Artist',
      'Nails at Home',
      'Men Grooming',
      'Henna Artist',
      'Bridal Makeup',
      'Waxing at Home',
      'Facial at Home',
    ],
  },
  {
    key: 'event-home-services',
    title: 'Event Home Services',
    titleAr: 'خدمات مناسبات منزلية',
    iconSlug: 'photography-video',
    slug: 'event-home-services',
    description: 'Home event setup, tents, catering support, furniture rental, and cleanup.',
    services: [
      'Event Setup',
      'Home Party Setup',
      'Tent Rental Setup',
      'Table & Chair Rental',
      'Coffee Hospitality Service',
      'Buffet Setup',
      'Balloon Decoration',
      'Event Cleanup',
      'Majlis Setup',
      'Outdoor Event Lighting',
    ],
  },
  {
    key: 'home-organization',
    title: 'Home Organization',
    titleAr: 'تنظيم المنزل',
    iconSlug: 'cleaning',
    slug: 'home-organization',
    description: 'Closet organization, storage systems, unpacking, and decluttering.',
    services: [
      'Closet Organization',
      'Kitchen Organization',
      'Storage Room Organization',
      'Decluttering',
      'Unpacking After Move',
      'Pantry Organization',
      'Kids Room Organization',
      'Home Inventory Setup',
    ],
  },
];

export const ALL_HOME_SERVICES: string[] = Array.from(
  new Set(HOME_SERVICE_GROUPS.flatMap((g) => g.services))
).sort((a, b) => a.localeCompare(b));

// Flat list of { label, category } for autocomplete suggestions
export const SERVICE_AUTOCOMPLETE_LIST: Array<{ label: string; category: string }> =
  HOME_SERVICE_GROUPS.flatMap((g) => [
    { label: g.title, category: 'Category' },
    ...g.services.map((s) => ({ label: s, category: g.title })),
  ]);

// Arabic autocomplete — uses titleAr as category; service labels stay English for now
export const SERVICE_AUTOCOMPLETE_LIST_AR: Array<{ label: string; category: string }> =
  HOME_SERVICE_GROUPS.flatMap((g) => [
    { label: g.titleAr, category: 'فئة' },
    ...g.services.map((s) => ({ label: s, category: g.titleAr })),
  ]);
