/** Key Houston metro neighborhoods and cities shown as selectable service areas for pros. */
export const HOUSTON_CITIES = [
  // Inner Houston
  'Downtown Houston',
  'Midtown',
  'Montrose',
  'Houston Heights',
  'River Oaks',
  'Galleria / Uptown',
  'Upper Kirby',
  'Greenway Plaza',
  'Medical Center',
  'Meyerland',
  'Memorial',
  'Spring Branch',
  'Energy Corridor',
  'Westchase',
  'Sharpstown',
  'Clear Lake',
  // Harris County suburbs
  'Katy',
  'Cypress',
  'Tomball',
  'Spring',
  'Humble',
  'Kingwood',
  'Atascocita',
  'Baytown',
  'Pasadena',
  'Deer Park',
  'Pearland',
  'Bellaire',
  // Fort Bend County
  'Sugar Land',
  'Missouri City',
  'Richmond / Rosenberg',
  'Fulshear',
  // Montgomery County
  'The Woodlands',
  'Conroe',
  'Magnolia',
  // Galveston County
  'League City',
  'Friendswood',
  'Webster / Nassau Bay',
  'Galveston',
];
