export const RIYADH_DISTRICTS = [
  'Al Olaya',
  'Al Malaz',
  'Al Murabbah',
  'Al Rawdah',
  'Al Sulaymaniyah',
  'Al Nakheel',
  'Al Hamra',
  'Al Sahafa',
  'Al Shuhada',
  'Al Wizarat',
  'Al Madinah',
  'Al Aziziyah',
  'Al Batha',
  'Al Dirah',
  'Al Faisaliyah',
  'Al Ghadir',
  'Al Jazirah',
  'Al Malqa',
  'Al Mansourah',
  'Al Murabba',
  'Al Naseem',
  'Al Qirawan',
  'Al Rabwah',
  'Al Uraija',
  'Al Yasmin',
  'Hittin',
  'Ishbiliyah',
  'King Fahd',
  'Qurtubah',
  'Salam',
] as const;

export type RiyadhDistrict = typeof RIYADH_DISTRICTS[number];
